### ISSUE TITLE
Curiosity

### ISSUE THREAD

**Issue by sadiqulislam** [SabujXi/LibraryManagementSystem-Django#28]
I wanted to Know What Is The Backend And Frontend Code Of This Project. I want To Start A New Project If I dont know What Is The Backend And What is The Frontend Side I wouldn't Start My Project

**Comment by SabujXi** [comment]
The templates, static files including css, js and related libraries, i.e. Bootstrap, jQuery, are the frontend code and the rest (=all those Python codes) are backend codes. So, practically speaking the html templates we are creating are the frontend codes.
